everest
`./everest pull`, after self-update, used to not update the working copies of each component of everest, printing the usage message instead. Then, I thought to have "fixed" this bug by commit d5023e2d56702140fd69c77df32372f1d9bfcbfa. Alas, due to this so-called "fix", everest actually lost the ability to run the new version of itself after self-updating.
In fact, the bug was due to the following: in a function such as self_update, `$@` contains the list of arguments to the function, not to the overall script.
This is why, this pull request aims to restore the ability for everest to run the new version of itself after self-updating, by first saving the script's remaining arguments, as well as options such as `--yes`, to separate `options` and `remaining_args` arrays before entering the …
=> ./everest pull: Call new version of ./everest after self-updating

.docker/everest-chomolungma/Dockerfile, everest
Upon commit 51e2c88557a84ae8a0e9f9a32037af977a8b8768, the Everest Docker image fails to build, because Z3 could not be found in PATH.
Indeed, the abovementioned commit pulls Z3 from FStarLang/binaries and makes PATH point there. This change to PATH is then made in `.bashrc` , which is not loaded when building the Docker image because `.bashrc` is only loaded in interactive shells, whereas the shell in which the Docker image is built cannot be interactive.
By contrast, `opam init --auto-setup` writes its changes to `.profile`, which is always loaded by login shells, whether interactive or not; thus, the Docker image has been built in such a way that all commands always run in a login shell. This way, OCaml is in the PATH when building the Docker image.
Given all of these, it means that …
=> Offer to store environment variables somewhere else than .bashrc

.gitignore, everest
These commands are there to make life with multiple git repositories a little easier. "forall" is a copy of the command of the same name from the repo tool used in Android: it simply executes a given command in all repositories. "merge" issues a "git pull --rebase" in all repositories, it only exists as a special command because it will re-start the everest script after update, the way "pull" does.
=> Fix up .gitignore, add commands "merge" and "forall" to everest script

opam-packages
This is what I've attempted after I did the above:
1. opam uninstall ctypes-foreign
2. ./everest check
3. ./everest make
Now I get that same error about ctypes.foreign.threaded not being found. So then:
4. Change the last line in opam-packages to: ctypes.foreign.unthreaded ctypes-foreign
5. ./everest check (This step notices the package is not installed and asks me to run install_all_opam_packages, for which I tell it yes, and then asks me to approve installing ctypes-foreign.)
6. ./everest make
Now the build succeeds.
=> Look for ctypes.foreign.unthreaded package instead of ctypes.foreign - fixes #56

everest
Make kremlin test use system OpenSSL
=> Fix #64 (kermlin test failing due to bad OpenSSL)

everest, repositories.sh
1- Use the new URLs for github repositories in `project-everest` instead of `mitls`
2- Pass `-k` to more make invocations
I did not change the URL for quackyducky (into everparse) since it would change the directory name, but I could that too if we agree.
=> Minor fixes

everest
Introduce an `--admit` option to pass in `--admit_smt_queries true` via `OTHERFLAGS`
=> Introduce --admit

everest
Mostly motivated by `./everest forall git grep blah`. If one of the
greps comes out empty, it also has a non-zero exit code and the script
will not run the command on the remaining repos (since we have -e). The
same happens when git invokes a pager (less) and one presses 'q' to
quit.
While at it use a subshell instead of cd-ing back to the parent
directory.
=> forall: continue on errors

everest
Does something like this already exists? It's a shortcut to updating every, or the named subprojects to master.
Would need a few tweaks before merging, but curious how the CI machine does this? Have I just missed the relevant command?
Here's an example of advancing F*:
```
./everest FStar advance
Advancing FStar
~/r/everest/FStar ~/r/everest
Already on 'master'
Your branch is behind 'origin/master' by 10 commits, and can be fast-forwarded.
(use "git pull" to update your local branch)
HEAD is now at 15fe9e9322 Merge branch 'master' of github:FStarLang/FStar
~/r/everest
```
I suppose it's similar to `./everest forall git pull`?
=> introduce 'everest advance'

everest
This PR introduces an `archive` subcommand to generate a compressed tarball with all the relevant sources for building (and checking) Everest. After extracting the tarball, hitting `make` will build all of Everest without needing an external connection--- not even for fetching vale, but working OCaml and z3 installs are required. The archive does not include any Git history, which is what saves the most space, nor any Git repos at all.
This is useful if one of us needs to reproduce a build failure and has a very poor connection (for whatever reason :-) ). The compressed archive is currently 25MB, while all of the Everest *repos* together take up 2GB. All the sources are about 248MB, so the compression factor is about 10x. The vale binaries, which seldom change, take up about 2MB of the …
=> introduce `everest archive`

everest
I tried to compile Everest on a fresh Ubuntu 18.04 LTS machine, by manually installing and initializing `opam` before running `./everest check`.
It turns out that, on such a fresh machine, `.bash_profile` initially does not exist, so `opam init` modifies `.profile` instead.
But then, `./everest` creates and modifies `.bash_profile`, which results in bash skipping `.profile`  at the next login; thus, the opam environment is no longer properly set.
To solve this issue, I make `./everest` modify `.profile` by default if `.bash_profile` does not exist.
Context: I am trying to write detailed instructions to compile EverParse on Linux, and I believe that asking the user to manually set `EVEREST_ENV_DEST_FILE` to account for this case is not user-friendly. We recently received feedback from a …
=> config file should be .profile if .bash_profile does not exist

everest
Yesterday I accidentally cleaned my entire build because `clean` is not using the project restriction. So I thought I improve the `help` text a bit. I tried to understand the best I could which commands take the restriction.
=> Indicate in help which commands can be restricted

.github/workflows/linux-x64.yaml
Sigh, to avoid errors if the token is not present, as in forked repos. See https://github.com/slackapi/slack-github-action/pull/124.
=> actions: conditional slack message

everest
The `everest shell` command spawns a subshell with the correct `FSTAR_HOME`/`HACL_HOME`/etc. environment variables set.  This makes it easy to run e.g. `cd mitls-fstar; make` to debug build failures.
=> Add `everest shell` command for debugging.

repositories.sh
Notably, this is not a functional change as this pulse-20240207 repo was moved into FStarLang and renamed pulse, so the old URL will resolve to this new one, but that's probably only temporary and unclear.
=> repositories.sh: point to new Pulse repo

.docker/build/linux/Dockerfile.OCaml, .docker/build/linux/Dockerfile.everest-move, everest, hashes.sh
With FStarLang/FStar#2770 now merged, Everest now works well with OCaml 4.14. So, with **this PR**:
* Everest CI to use OCaml 4.14
* `./everest check` to download OCaml 4.14 on Windows
=> Switch to OCaml 4.14

everest, get_fstar_z3.sh
Preparing for F* upgrading to z3-4.13.3 in https://github.com/FStarLang/FStar/pull/3631
This PR copies FStar/bin/get_fstar_z3.sh, which downloads the right versions of Z3 for each platform
And updates the everest script to call get_fstar_z3.sh instead of relying on FStarLang/binaries
=> add downloading z3 4.13.3 and 4.8.5 to the everest script

.docker/build/everest-move-fun.sh, get_fstar_z3.sh
This script is taken from the F* repo and shouldn't be edited here. This patch makes it update on every everest move.
=> Automatically updating the get_fstar_z3 script on an upgrade

everest
Pulse relies on checked files for internal compiler modules, after https://github.com/FStarLang/pulse/pull/246.
We use to avoid this need by keeping an OCaml snapshot of the checker in the Pulse repo, but we've removed that since. That was not ideal due to merge conflicts and etc, but also meant that an everest build would not check that Pulse can successfully build.
This changes the F* build rule to add the bootstrapping step.
--
This means an everest build will now be a bit slower. I am also wondering if we still want Pulse in the everest set of projects.
cc @tahina-pro @gebner @msprotz
=> everest: bootstrap F*, now required for building Pulse

everest
I'll add this so we cant test the pulse2rust component of pulse. An alternative is exporting `PULSE_NO_RUST=1` to disable these (https://github.com/FStarLang/pulse/pull/297), so if installing this in undesirable we can switch to that.
=> Installing bindgen-cli, for pulse

everest
This PR updates everest for https://github.com/FStarLang/FStar/pull/3637, though we should settle https://github.com/FStarLang/FStar/discussions/3655 first.
The last patch includes a set of hashes that successfully built locally, that should not be merged, just including it to checkpoint.
=> Updating for new F* build

.docker/build/build.sh, .docker/build/everest-move.sh
Projects with hints should set the flag, and projects that do not use hints (like F*) must not have this flag set. Otherwise it can change the behavior of warnings and error messages, which we test for.
=> ci: do not set OTHERFLAGS=--use_hints

.docker/build/linux/Dockerfile.OCaml, .docker/build/linux/Dockerfile.everest-move, everest
F* and check world are now running OCaml 5.3.0 (though we support older versions too). Pulse in particular added a test that uses domainslib, and that failed during the everest upgrade due to now having the package installed. I'm here passing a flag to skip that test (this will fail until https://github.com/FStarLang/pulse/pull/440 is merged), but also bumping the OCaml version to 5.3.0.
If staying on an older OCaml is preferable that patch can be reverted.
=> Use OCaml 5.3.0, fix Pulse test (by skipping it)

.docker/build/linux/Dockerfile.OCaml, .docker/build/linux/Dockerfile.everest-move, hashes.sh
And advance all hashes manually, to see if this builds everparse properly. If that does not work, I think we should disable the building of COSE in the default everparse rule (COSE is not a component of everparse, it's an example).
=> docker: bump to Ubuntu 24.10

everest, lib.sh
This prints the environment variables to set in a sourceable format, similar to opam env and others. There is already `everest shell`, but the subshell will read user dotfiles like `.bash_aliases` and potentially override some of these variables.
```
$ ./everest env
FSTAR_EXE='/home/guido/r/everest/master/FStar/bin/fstar.exe'; export FSTAR_EXE;
FSTAR_HOME='/home/guido/r/everest/master/FStar/'; export FSTAR_HOME;
VALE_HOME='/home/guido/r/everest/master/vale'; export VALE_HOME;
KRML_HOME='/home/guido/r/everest/master/karamel'; export KRML_HOME;
PULSE_HOME='/home/guido/r/everest/master/pulse/out'; export PULSE_HOME;
STEEL_HOME='/home/guido/r/everest/master/steel'; export STEEL_HOME;
HACL_HOME='/home/guido/r/everest/master/hacl-star'; export HACL_HOME; …
```
=> Introduce `everest env`
